# Generated by Django 3.2.9 on 2022-07-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.IntegerField(primary_key=True, serialize=False)),
                ('case_type', models.CharField(max_length=40)),
                ('loc', models.CharField(max_length=80)),
                ('pincode', models.IntegerField()),
                ('case_details', models.CharField(max_length=200)),
            ],
        ),
    ]
