# Generated by Django 3.2.9 on 2022-07-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220710_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report1',
            new_name='Report',
        ),
    ]
