# Generated by Django 3.2.9 on 2022-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220703_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report1',
            fields=[
                ('Fir_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Dhaara', models.CharField(max_length=50)),
                ('Police_St_ID', models.IntegerField()),
                ('Location', models.CharField(max_length=80)),
                ('Case_Details', models.CharField(max_length=200)),
                ('Date_Time', models.DateTimeField()),
                ('longitute', models.DecimalField(decimal_places=10, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
